data:
  image: aexea/aexea-base
  volumes:
    - /home/uid1000
web:
  build: .
  entrypoint: ./manage.py
  command: "runserver 0.0.0.0:8000"
  environment:
      PYTHONUNBUFFERED: 0
  volumes:
   - .:/opt/code
  volumes_from:
   - data
  ports:
   - "8000:8000"
  external_links:
   - axmeta_rabbitmq_1:rabbitmq
   - axmeta_db_1:db
celery:
  build: .
  entrypoint:
    - "celery"
  command: "-n {{ project_name }}.%h -A {{ project_name }} worker --loglevel=info"
  environment:
    PYTHONUNBUFFERED: 0
  volumes:
   - .:/opt/code
  external_links:
   - axmeta_rabbitmq_1:rabbitmq
   - axmeta_db_1:db
